import webbrowser
import pyautogui
import time







chrome_path = 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'



def download():
     x = 0
     y = input('enter:')

     first = ['l',  'M', 'Q', 'U', 'Y', 'c', 'g']

     url0 = 'https://gogo-stream.com/download?id=MTA3Mz'+first[x]+'w&refer=https://ww2.narutoshippudenepisodes.com/'
     url1 = 'https://gogo-stream.com/download?id=MTA3Mz'+first[x]+'x&refer=https://ww2.narutoshippudenepisodes.com/'
     url2 = 'https://gogo-stream.com/download?id=MTA3Mz'+first[x]+'y&refer=https://ww2.narutoshippudenepisodes.com/'
     url3 = 'https://gogo-stream.com/download?id=MTA3Mz'+first[x]+'z&refer=https://ww2.narutoshippudenepisodes.com/'
     url4 = 'https://gogo-stream.com/download?id=MTA3Mz'+first[x]+'0&refer=https://ww2.narutoshippudenepisodes.com/'
     url5 = 'https://gogo-stream.com/download?id=MTA3Mz'+first[x]+'1&refer=https://ww2.narutoshippudenepisodes.com/'
     url6 = 'https://gogo-stream.com/download?id=MTA3Mz'+first[x]+'2&refer=https://ww2.narutoshippudenepisodes.com/'
     url7 = 'https://gogo-stream.com/download?id=MTA3Mz'+first[x]+'3&refer=https://ww2.narutoshippudenepisodes.com/'
     url8 = 'https://gogo-stream.com/download?id=MTA3Mz'+first[x]+'4&refer=https://ww2.narutoshippudenepisodes.com/'
     url9 = 'https://gogo-stream.com/download?id=MTA3Mz'+first[x]+'5&refer=https://ww2.narutoshippudenepisodes.com/'


     webbrowser.open_new_tab(url0)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url1)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url2)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url3)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url4)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url5)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url6)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url7)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url8)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url9)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     x = int(x)+1
     y = y+1
     webbrowser.open_new_tab(url0)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url1)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url2)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url3)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url4)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url5)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url6)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url7)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url8)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url9)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     x = int(x)+1
     y = y+1
     webbrowser.open_new_tab(url0)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url1)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url2)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url3)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url4)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url5)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url6)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url7)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url8)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url9)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     x = int(x)+1
     y = y+1
     webbrowser.open_new_tab(url0)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url1)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url2)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url3)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url4)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url5)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url6)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url7)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url8)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url9)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     x = int(x)+1
     y = y+1
     webbrowser.open_new_tab(url0)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url1)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url2)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url3)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url4)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url5)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url6)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url7)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url8)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url9)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     x = int(x)+1
     y = y+1
     webbrowser.open_new_tab(url0)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url1)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url2)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url3)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url4)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url5)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url6)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url7)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url8)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     y = int(y)+1
     webbrowser.open_new_tab(url9)
     time.sleep(5)
     pyautogui.click(750, 450)
     time.sleep(5)
     pyautogui.write(str(y), interval=0.15)
     pyautogui.click(790, 505)
     time.sleep(40)
     pyautogui.click(1900, 15)
     x = int(x)+1
     y = y+1

download()


#python -u C:\Users\vidit\Documents\CODE\ddownload.py
